apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: c0nuoew45-go 
  janus-idp.io/tekton: c0nuoew45-go
  backstage.io/kubernetes-id: c0nuoew45-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c0nuoew45-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml